####Dummy variables part

In [1]:
import numpy as np
import pandas as pd


In [5]:
df = pd.read_csv('/content/Locations_with_prices.csv')
df

town  area   price
0      zhob  2000  200000
1      zhob  2100  210000
2      zhob  2200  220000
3      zhob  2300  230000
4      zhob  2400  240000
5   sherani  2000  150000
6   sherani  2100  160000
7   sherani  2200  170000
8   sherani  2300  180000
9   sherani  2400  190000
10   lorlai  2000  170000
11   lorlai  2100  180000
12   lorlai  2200  190000
13   lorlai  2300  200000
14   lorlai  2400  210000

In [9]:
dummies = pd.get_dummies(df.town)
dummies

lorlai  sherani  zhob
0        0        0     1
1        0        0     1
2        0        0     1
3        0        0     1
4        0        0     1
5        0        1     0
6        0        1     0
7        0        1     0
8        0        1     0
9        0        1     0
10       1        0     0
11       1        0     0
12       1        0     0
13       1        0     0
14       1        0     0

###merge the dummy data to our original dataFrame or data table

In [10]:
merged= pd.concat([df,dummies],axis='columns')
merged

town  area   price  lorlai  sherani  zhob
0      zhob  2000  200000       0        0     1
1      zhob  2100  210000       0        0     1
2      zhob  2200  220000       0        0     1
3      zhob  2300  230000       0        0     1
4      zhob  2400  240000       0        0     1
5   sherani  2000  150000       0        1     0
6   sherani  2100  160000       0        1     0
7   sherani  2200  170000       0        1     0
8   sherani  2300  180000       0        1     0
9   sherani  2400  190000       0        1     0
10   lorlai  2000  170000       1        0     0
11   lorlai  2100  180000       1        0     0
12   lorlai  2200  190000       1        0     0
13   lorlai  2300  200000       1        0     0
14   lorlai  2400  210000       1        0     0

##We will drop one of the dummy column for best result and also our town columns because we will give the numeric data to our model

In [11]:
final = merged.drop(['town', 'lorlai'],axis='columns')
final

area   price  sherani  zhob
0   2000  200000        0     1
1   2100  210000        0     1
2   2200  220000        0     1
3   2300  230000        0     1
4   2400  240000        0     1
5   2000  150000        1     0
6   2100  160000        1     0
7   2200  170000        1     0
8   2300  180000        1     0
9   2400  190000        1     0
10  2000  170000        0     0
11  2100  180000        0     0
12  2200  190000        0     0
13  2300  200000        0     0
14  2400  210000        0     0

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

##Drop the price column

In [13]:
X = final.drop('price' , axis= 'columns')
X

area  sherani  zhob
0   2000        0     1
1   2100        0     1
2   2200        0     1
3   2300        0     1
4   2400        0     1
5   2000        1     0
6   2100        1     0
7   2200        1     0
8   2300        1     0
9   2400        1     0
10  2000        0     0
11  2100        0     0
12  2200        0     0
13  2300        0     0
14  2400        0     0

In [15]:
y = final.price
y

0     200000
1     210000
2     220000
3     230000
4     240000
5     150000
6     160000
7     170000
8     180000
9     190000
10    170000
11    180000
12    190000
13    200000
14    210000
Name: price, dtype: int64

In [16]:
model.fit(X,y)

LinearRegression()

##Here i want to make 1,0 for predicting the sherani price. same as if you want to print the price of zhob then 0,1 after area in predict method.

In [21]:
model.predict([[2000,1,0]])   #for sherani

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([150000.])

In [22]:
model.predict([[2000,0,1]])     # for zhob

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([200000.])

In [23]:
model.predict([[2000,0,0]])    #waist winser where both are zer0

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([170000.])

##Accuracy of the predicated values

In [24]:
model.score(X,y)

1.0

###One hot encoding part

In [128]:
import pandas as pd

In [129]:
df = pd.read_csv("/content/Locations_with_prices.csv")
df

town  area   price
0      zhob  2000  200000
1      zhob  2100  210000
2      zhob  2200  220000
3      zhob  2300  230000
4      zhob  2400  240000
5   sherani  2000  150000
6   sherani  2100  160000
7   sherani  2200  170000
8   sherani  2300  180000
9   sherani  2400  190000
10   lorlai  2000  170000
11   lorlai  2100  180000
12   lorlai  2200  190000
13   lorlai  2300  200000
14   lorlai  2400  210000

In [130]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

###To convert the town names into numeric data

In [131]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      2  2000  200000
1      2  2100  210000
2      2  2200  220000
3      2  2300  230000
4      2  2400  240000
5      1  2000  150000
6      1  2100  160000
7      1  2200  170000
8      1  2300  180000
9      1  2400  190000
10     0  2000  170000
11     0  2100  180000
12     0  2200  190000
13     0  2300  200000
14     0  2400  210000

In [132]:
X = dfle[['town','area']].values

In [133]:
X

array([[   2, 2000],
       [   2, 2100],
       [   2, 2200],
       [   2, 2300],
       [   2, 2400],
       [   1, 2000],
       [   1, 2100],
       [   1, 2200],
       [   1, 2300],
       [   1, 2400],
       [   0, 2000],
       [   0, 2100],
       [   0, 2200],
       [   0, 2300],
       [   0, 2400]])

In [134]:
y = dfle.price.values
y

array([200000, 210000, 220000, 230000, 240000, 150000, 160000, 170000,
       180000, 190000, 170000, 180000, 190000, 200000, 210000])

In [141]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')   ##First column into one hot encodeing

In [136]:
X = ct.fit_transform(X)
X

array([[0.0e+00, 0.0e+00, 1.0e+00, 2.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.1e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.2e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.4e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.0e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.2e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.3e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.4e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.1e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.3e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 2.4e+03]])

In [137]:
X = X[:,1:]

In [138]:
X

array([[0.0e+00, 1.0e+00, 2.0e+03],
       [0.0e+00, 1.0e+00, 2.1e+03],
       [0.0e+00, 1.0e+00, 2.2e+03],
       [0.0e+00, 1.0e+00, 2.3e+03],
       [0.0e+00, 1.0e+00, 2.4e+03],
       [1.0e+00, 0.0e+00, 2.0e+03],
       [1.0e+00, 0.0e+00, 2.1e+03],
       [1.0e+00, 0.0e+00, 2.2e+03],
       [1.0e+00, 0.0e+00, 2.3e+03],
       [1.0e+00, 0.0e+00, 2.4e+03],
       [0.0e+00, 0.0e+00, 2.0e+03],
       [0.0e+00, 0.0e+00, 2.1e+03],
       [0.0e+00, 0.0e+00, 2.2e+03],
       [0.0e+00, 0.0e+00, 2.3e+03],
       [0.0e+00, 0.0e+00, 2.4e+03]])

In [139]:
model.fit(X,y)

LinearRegression()

In [140]:
model.predict([[0,1,3400]]) # 3400 sqr ft home in zhob

array([340000.])

In [142]:
model.score(X,y)

1.0